# Generated by Django 3.0.2 on 2022-05-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=30)),
                ('currency_buying', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('currency_selling', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('currency_rate_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
